my-example-job:
   stage:                           build # One of the stages listed below this job (required)
   image:                           0mustafasevinc0/cargo20200601:1.0 # Any docker image (required)
   timeout:                         3 hours 30 minutes
   artifacts:
      paths:                        
        - build/
   script:
     - echo "List of shell commands to run in your jobgggg"
     - echo "You can also just specify a script here, like so:"
     - mkdir build
     - cargo +nightly-2020-06-01 build
     - mv /target/release /build
